package com.imooc.test;

import java.util.InputMismatchException;
import java.util.Scanner;

public class TryDemoThree {
	
	public static int test() throws ArithmeticException{
		Scanner sc = new Scanner(System.in);
		try {
			int one = sc.nextInt();
			int two = sc.nextInt();
			System.out.println("1/2:" + one / two);
			return one/two;
		} 
//		catch (ArithmeticException e) {
////			e.printStackTrace();
//			System.exit(1);
//			System.out.println("算数异常：" + e);
//		} catch (InputMismatchException e) {
//			System.out.println("输入异常：" + e);
//		} 
		catch (Exception e) {
			System.out.println("其他异常：" + e);
			return 0;
		} finally {
			System.out.println("运算结束");
		}
	}
	
	public static void main(String[] args) {
		int result = test();
		System.out.println(result);
		
	}
}
